### ISSUE TITLE
Подготовить диаграммы в draw.io

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#1]
Предыстория:

Во время обсуждения на прошлых встречах были составлены диаграммы и блок-схемы, которые визуально отображают пошаговую работу проекта.

План решения:

Воссоздать все диаграммы и блок-схемы в draw.io.

Планируемое время работы:

2 часа

**Comment by Kitamuro** [comment]
Диаграмма процесса транзакции завершена.
Файл диаграммы приложен ниже.
[https://drive.google.com/file/d/1MS1TQhAF7mD9EU4vnqhjGPNqr2Iw2scc/view?usp=sharing](url)

**Comment by Kitamuro** [comment]
Диаграмма процесса транзакции и функций(админ панель, кабинет коммерсанта) завершены.
Файл диаграммы приложен ниже.
Диаграмма транзакции
[https://drive.google.com/file/d/1MS1TQhAF7mD9EU4vnqhjGPNqr2Iw2scc/view?usp=sharing](url)
Диаграмма функций(админ панель, кабинет коммерсанта)
[https://drive.google.com/file/d/1YUa3aBdegzJ_VTdcyi5NymslHpy_8wEV/view?usp=sharing](url)
