### ISSUE TITLE
Вызов страницы оплаты со страницы оформления заказа (10h:5h)

### ISSUE THREAD

**Issue by Zhanel-K** [AS-Java/Payment-Module#17]
**Тип задачи:**  enhancement 
**Заголовок:**  Необходимо переделать страницу оформления заказа и страницу оплаты
**Описание:**  На текущий момент страница оформления заказа подвязана к MVC контролеру. Необходимо:
1. Убрать MVC контроллер для страницы оформления заказа и страницы оплаты. Данный функционал был создан для демонстрации заказчику. Однако наша основная цель - это предусмотреть оправку данных на сервер с минимальным "вмешательством" со стороны коммерсанта. 
2. Реализовать через JS формирование страницы оплаты и отправку на сервер REST post запроса на сервер (REST controller создан уже).
3. Примерное решение можно посмотреть на сайте Тинькофф: https://oplata.tinkoff.ru/develop/widget/install/ - именно эту форму коммерсант вставляет себе на страницу. 
**Конечный результат:** формирование страницы оплаты со страницы оформления заказа и отправка ПОСТ запроса на наш сервер через REST API.
Планируемое время работы: 10 часов.
Затраченное время работы: 5 часов.
**Задача реализована не до конца.**

**Comment by Zhanel-K** [comment]
к работе подключен Чингиз. Необходимо распределить работу так, чтобы успеть в срок, к понедельнику.

**Comment by is-art** [comment]
> к работе подключен Чингиз. Необходимо распределить работу так, чтобы успеть в срок, к понедельнику.

В окне странице оплаты  нужно отобразить данные о заказе покупателя ( номер заказа , название магазина , список товаров ,  сумму ) эти же данные нужно отправить и принять на сервере.

**Comment by Kitamuro** [comment]
К работе подключен Артур для полного завершения страницы оплаты( вывод информации о заказе покупателя и отправки их также на сервер ).
