### ISSUE TITLE
Определить технические требования кабинета коммерсанта

### ISSUE THREAD

**Issue by Zhanel-K** [AS-Java/Payment-Module#2]
Составить техническое задание функционала "кабинет коммерсанта" с подробным описание каждого пункта:
1. транзакции операций;
2. аналитика;
3. возмещение денег коммерсанту;
4. отчеты;
5. данные компании.
Как должен быть реализован каждый из пунктов. 
к прочтению: техническое задание заказчика, и все собранные на текущий момент артефакты, протокола встреч, аудио и диаграммы.

**Comment by ChingizYussuf** [comment]
https://docs.google.com/document/d/1Pv7xgtjVMHMGRQovu2VD52YVIJZPTbv-7Rd9C-JEnMM/edit?usp=sharing

**Comment by is-art** [comment]
> https://docs.google.com/document/d/1Pv7xgtjVMHMGRQovu2VD52YVIJZPTbv-7Rd9C-JEnMM/edit?usp=sharing

Не соответствует требованиям задания.

**Comment by ChingizYussuf** [comment]
https://docs.google.com/document/d/1Pv7xgtjVMHMGRQovu2VD52YVIJZPTbv-7Rd9C-JEnMM/edit

**Comment by Zhanel-K** [comment]
Необходимо подробно расписать каждый функционал кабинета коммерсанта на примере Тинькофф. Видел предоставлено. Желательно прочитать еще раз общее техническое требование и протокол встречи 2 с заказчиком.

**Comment by is-art** [comment]
Описал примерный функционал страницы  кабинета коммерсанта.
[Ссылка на описание](https://docs.google.com/document/d/1Pv7xgtjVMHMGRQovu2VD52YVIJZPTbv-7Rd9C-JEnMM/edit)
Время выполнения : 3 часа

**Comment by ChingizYussuf** [comment]
Потратил время на: 
Прослушавание встречи1 - 2 часа; 
Просмотр видео примеров - 40 минут;
Прочтение ответов заказчика в телегрем - 30 минут;
Прочтение ответов заказчика в диске - 30 минут;
