### ISSUE TITLE
Минимальные тесты для проекта

### ISSUE THREAD

**Issue by Kitamuro** [AS-Java/Payment-Module#22]
Task: Реализовать несколько модульных тестов
Конечный результат: 2-3 модульных теста класса ApacheHTTPClient
План решения: Внести изменения в ApacheHTTPClient с целью возможной реализации юнит тестов. Добавление dependecy и создание в директории  TEST  соответствующего тестового класса с несколькими тестами.
Планируемое время работы: 10 часов.
Затраченное время работы: 6 часов.

**Comment by Zhanel-K** [comment]
Добавлено три теста в src/test/java/school/attractor/payment_module/domain/ApacheHttp/ApacheHttpClientTest

**Comment by is-art** [comment]
проверил. нет возможности проверки  ApacheHTTPClient , доработка тестов  будет вестись по #30 тикету.
