### ISSUE TITLE
Добавить preloader на страницу оплаты

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#26]
Добавить анимацию загрузки  на страницу оплаты ,  можно использовать  любую библиотеку 

Планируемое время выполнения : 2 часа

**Comment by Kitamuro** [comment]
Поменял анимацию загрузки на круговую бесконечную загрузку прогресса(2 часа)
Приступаю к отображению ответа(успешного или провального)

**Comment by is-art** [comment]
Проверил, все работает.
