### ISSUE TITLE
Отображение ответа от банка (10h : 5h30m)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#28]
Отображение ответа от банка

**Comment by Kitamuro** [comment]
Добавил методы и обработку запроса в банк (1:30h)

**Comment by Kitamuro** [comment]
Вывел ответ банка, нужно создать разметку и визуально показать ответ. Добавил триггер длительности анимации

**Comment by Kitamuro** [comment]
Закончил вывод ответа банка.
Отправляя запрос в банк появляется анимация загрузки и через 3 секунды получаем ответ от банка. Смотря от его ответа будем показывать либо успешное либо неуспешное выполнение транзакции
