### ISSUE TITLE
Получение данных из БД по транзакциям(5h:2h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#32]
Task: Получение данных из БД по транзакциям
Конечный результат: Внести изменения в контроллер с выводом транзакций из БД
Планируемое время работы: 5 часов.
Затраченное время работы: 2 часа

**Comment by Zhanel-K** [comment]
Пока реализация начата на базе Mysql. Задача связана с тикетом #34 . Как только он будет реализован, данная задача будет завершена.

**Comment by Zhanel-K** [comment]
Тикет закоммичен вместе с тикетом #35, готов к тестированию

**Comment by Kitamuro** [comment]
Проверил, все работает!
