### ISSUE TITLE
Пагинация для вывода списка транзакций(10h:5h)

### ISSUE THREAD

**Issue by ChingizYussuf** [AS-Java/Payment-Module#35]
Task: Пагинация для вывода списка транзакций
Конечный результат: Пагинация для вывода списка транзакций в кабинете коммерсанта
План решения: Добавить пагинацию с использованием thymeleaf и JPA. 
Планируемое время работы: 10 часов.
Затраченное время работы: 5 часов

**Comment by Zhanel-K** [comment]
тикет готов к тестированию

**Comment by Kitamuro** [comment]
Проверил, все работает!
