### ISSUE TITLE
Добавление возможности поиска на страницу отчета транзакций(10h : 12h)

### ISSUE THREAD

**Issue by ChingizYussuf** [AS-Java/Payment-Module#36]
**Задачи**:
1. Добавить фильтры по статусу, идентификатору транзакции и магазину в наш сервис.
2. Добавить форму поиска по фильтрам в транзакциях на странице транзакций в кабинете коммерсанта.

**В конце должно быть:**
1. Красивый графический интерфейс поиска транзакций по фильтрам
![операции](https://user-images.githubusercontent.com/33262734/79750336-9a62ef80-8332-11ea-924e-94b663518923.png)

2. Рабочие методы для поиска по фильтрам

**По возможности:**
Добавить поиск по разным фильтрам
Например: Если пользователь ввел только название магазина а остальные пустые то делать фильтрацию по магазинам. Если пользователь ввел только статус и идентификатор то только по этим двум параметрам т.е объект должен будет принимать и null значения только обрабатывать их.

**Comment by Kitamuro** [comment]
**Добавил**
1. Класс для приема данных пользователя с формы поиска.
2. Методы в репозиторий(для выдачи транзакций по статусу, ID, названию магазина.
3. Методы в сервис для обработки и выдачи данных.
4. Метод в CommersantController(пока полностью не работает).
5. Разметку на страницу Транзакции

Потрачено **6 часов**


**Нужно доделать:**
1. Прием разных данных и в зависимости от них выдать нужную информацию.
2. Правильно вывести результат поиска

**Comment by Kitamuro** [comment]
**Добавил:**
Вывод по разным параметрам поиска с пагинацией.

Потрачено **6 часов**

**В целом задача выполнена и работает корректно**
