### ISSUE TITLE
Изучить  формирование реестров.(10h : 8h)

### ISSUE THREAD

**Issue by ChingizYussuf** [AS-Java/Payment-Module#37]
Требование по задаче:
Изучить реестры со стороны банка и коммерсанта. Полное взаимодействие функционала и написать документацию максимально подробно и просто для понимания для других разработчиков

**Comment by Kitamuro** [comment]
Требование по задаче:
Изучить реестры со стороны банка и коммерсанта. Полное взаимодействие функционала и написать документацию максимально подробно и просто для понимания для других разработчиков

**Comment by ChingizYussuf** [comment]
[Документация формирование реестров](https://github.com/AS-Java/Payment-Module/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-%D1%80%D0%B5%D0%B5%D1%81%D1%82%D1%80%D0%BE%D0%B2)

**Comment by Kitamuro** [comment]
Прочитал, предложил подробнее узнать про реализацию реестров у заказчика.
