### ISSUE TITLE
Изучить функционал возврата транзакций для клиента коммерсанта, изучить документацию банка.(10h : 8h)

### ISSUE THREAD

**Issue by ChingizYussuf** [AS-Java/Payment-Module#38]

**Comment by Kitamuro** [comment]
Требование по задаче: 
Узнать как в целом происходит функционал возврата транзакции клиента коммерсанта.(Изучить документацию банка, как он работает с этим). 
И самое главное сделать свою документацию с работой над возвратом транзакции для других разработчиков. Максимально развернуто и понятно.

**Comment by ChingizYussuf** [comment]
[Документация возврата транзакций для клиента коммерсанта](https://github.com/AS-Java/Payment-Module/wiki/%D0%92%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%82-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B9-%D0%B4%D0%BB%D1%8F-%D0%BA%D0%BB%D0%B8%D0%B5%D0%BD%D1%82%D0%B0-%D0%BA%D0%BE%D0%BC%D0%BC%D0%B5%D1%80%D1%81%D0%B0%D0%BD%D1%82%D0%B0)

**Comment by Kitamuro** [comment]
Проверил. Поговорил с разработчиком, предложил некоторые корректировки.
