### ISSUE TITLE
Добавить подробные детали для каждой транзакции.

### ISSUE THREAD

**Issue by Kitamuro** [AS-Java/Payment-Module#39]
**Задачи:**
Добавить дополнительную информацию каждой транзакции(пока все что есть в нашей транзакции все вывести(возвраты, имя держателя карты, и тд))

**Как должно выглядеть в конце:**
В странице транзакции при нажатии на определенную транзакцию выводится окно с дополнительной информацией о платеже.
![инфо_о_транзакции](https://user-images.githubusercontent.com/33262734/79751012-b31fd500-8333-11ea-9039-8ef0d6911165.png).

**Comment by is-art** [comment]
Добавил события на клик по транзакции , теперь появляется окно с подробной информацией
Добавил кнопку закрыть, то бы  скрыть окно с подробной информацией  
Потратил 4 часа
