### ISSUE TITLE
Добавить возврат транзакции из кабинета коммерсанта (15h:9h)

### ISSUE THREAD

**Issue by Kitamuro** [AS-Java/Payment-Module#40]
**Задача**
Добавить возможность отменить/вернуть транзакцию в кабинете коммерсанта, в том числе частичную. 

**Дополнительно**
Изучить документацию отмены транзакций в облачном хранилище есть подробная информация).

**План решения** 
- Добавить на странице списка транзакций форму отправки запроса на возврат суммы, в том числе частичной. 
- Добавить обработку пост запроса на возврат в CommersantControllere, в том числе сохранение статуса Возвращен в Транзакции. 
- Внесение изменений в класс ApacheHttpClient так, чтобы можно было отправлять запрос в Банк с разными  TRTYPE, при этом для типов SalesCompletion и для Reverse один формат запроса, а для авторизации и для мгновенного списывания другой формат запроса.  
- Добавление List<Response> responses в класс Transaction для хранения истории запросов.
- Добавление таблицы Responses в базу данных.
- Внесение изменений в ControllerRest  в обработку пост запроса ("/pay") в связи с внесенными изменениями

**Не выполнено**
- Возможность частичной отмены транзакции: проверка суммы и TRTYPE

Планируемое время работы: 15 часов.
Затраченное время работы: 9 часов

**Comment by Zhanel-K** [comment]
Отправка запроса в Банк закомичена. Проверка функционала с отправкой запроса в Банк пока невозможна.

**Comment by Zhanel-K** [comment]
Реализация частичной отмены транзакции: проверка суммы и TRTYPE следует перенести на следующую итерацию
