### ISSUE TITLE
Холдирование средств при проведении транзакции коммерсанта (7h:2h)

### ISSUE THREAD

**Issue by Kitamuro** [AS-Java/Payment-Module#41]
**Описание**
У нас сейчас реализована функция автоматического платежа( т.е когда клиент коммерсанта выполняет платеж, с его счета сразу выписываются деньги) Теперь нам надо реализовать другую возможность платежа.

**Задача**
Добавить возможность производить холдирование( от слова hold ) средств. Это второй тип платежа. Его особенность в том, что когда коммерсант производит оплату сначала деньги замораживаются, а потом при его подтверждении они снимаются. 

Подробно можно прочитать [https://info.paymaster.ru/blog/holdirovanie-sredstv/](url)
и также в нашем облачном хранилище заказчик добавил дополнительную информацию.

**План решения**
- Добавить в конструктор  ApacheHttpClient входным параметром TRTYPE, от которого зависит тип запроса в Банк salesCompletion или Authorization или Reverse.
- Предусмотреть соответствующее поле hold в Transaction, которое в дальнейшем будет определяться настройками в кабинете коммерсанта, т.е. для каждого магазина коммерсанта отдельный тип списания.
- Добавить отправку запроса на salesCompletion из кабинета коммерсанта после отправки товара клиенту.

**Не выполнено**
Пост запрос из кабинета коммерсанта

Планируемое время работы: 7 часов.
Затраченное время работы: 2 часа.

**Comment by Zhanel-K** [comment]
Пост запрос из кабинета коммерсанта необходимо перенести на следующие итерации.
