### ISSUE TITLE
Переделать дизайн поиска транзакций(5h : 1:20h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#48]
Внести изменения в дизайн поиска транзакции

**Конечный результат:** 
Дизайн поиска транзакции должен быть идентичен прототипу

**План решения:** 
- На странице транзакции во вкладку поиска внести изменения

**Мотивация:** 
На данный момент коммерсант может найти
**Критерии приёмки:**
> Дизайн поиска транзакции должен быть идентичен прототипу

Планируемое время работы:
5 часов

**Comment by Kitamuro** [comment]
**Выполнено:**
Отрефакторил код стилей и добавил выборку по статусу и внес мелкие изменения.

**Потрачено**: 30 минут

**Comment by Kitamuro** [comment]
**Выполнил:**
Изменил дизайн согласно макету

**Потрачено:** 40 минут

**Comment by Zhanel-K** [comment]
Проверено.
