### ISSUE TITLE
Добавить сборку docker контейнера (15h : 19:30h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#49]
Реализовать сборку docker контейнера проекта

**Конечный результат:** 
Запуск docker файла собирает проект  нашего сервиса

**План решения:** 
- 

**Мотивация:** 
На данный момент выгрузка и обновление проекта осуществляются вручную.
**Критерии приёмки:**
> При запуске docker файла собирается проект

Планируемое время работы:
15 часов

**Comment by Kitamuro** [comment]
Приступил к изучению информации по DockerHub и JIB Maven Plugin 

**Потрачено** 3 часа
**Цели**
1. Попробовать вручную создать образ приложения.
2. Загрузить в свой DockerHub для тестирования образа.
3. Приступить к нашему проекту со всеми полученными знаниями

**Comment by Kitamuro** [comment]
Дальше изучал документацию и искал правильный путь к решению задачи. Приступил к ручному созданию образа и столкнулся с ошибкой с которой долго разбирался. Обратившись за помощью решил данную проблему. Получилось создать образ приложения.

**Потрачено** 15 часов

Цели: 
1. Загрузить тестовый образ на DockerHub и протестировать
2. Создать образ нашего приложения
3. Загрузить в DockerHub

**Comment by Kitamuro** [comment]
С помощью compose получилось настроить сеть между контейнерами и ошибка возникшая из-за подключения к БД исчезла. В результате чего получилось реализовать запуск проекта через docker

**Потрачено** 1:30 часа

Оставшиеся цели в стадии тестирования. Но они не входили в задачи поэтому передаю тикет в **In test**
