### ISSUE TITLE
Ввести единую терминологию проекта

### ISSUE THREAD

**Issue by Zhanel-K** [AS-Java/Payment-Module#5]
Описать и завести в Wiki  терминологию проекта, например, коммерсант, клиент коммерсанта и т.д.

**Comment by hekonnote** [comment]
№5 Ввести единую терминологию проекта

Надо кратко и тезисно описывать термины, понятия и сокращения, используемые в проекте на текущий момент. Данный перечень будет дополняться по мере необходимости.

Ссылка на текущую версию перечня https://drive.google.com/open?id=18eNd_VK2PYvCptPpoJqQgnxRS2q8T6dxPTC8TRUKzik
