### ISSUE TITLE
Реализовать возможность сохранения и отображения историй изменения транзакций(15h:15h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#50]
Реализовать сохранения и отображения истории изменений транзакции

**Конечный результат:** 
Добавить коммерсанту возможность видеть историю изменения транзакции.

**План решения:** 
- На странице транзакции в детализации добавить отображение истории транзакции.
- Добавить таблицу, которая будет хранить изменения транзакции: отклонена, подтверждена, возвращена частична или возвращена полностью.

**Мотивация:** 
На данный момент коммерсант может только просмотреть текущий статус транзакции.
**Критерии приёмки:**
> На странице транзакции в детализации можно просмотреть историю изменений транзакции: дату и время изменения и статус по каждому изменению.

Планируемое время работы:
15 часов

**Comment by is-art** [comment]
@Zhanel-K 
Добавил возможность отображения истории транзакций у заказа
Затраченное время 15 часов

**Comment by Zhanel-K** [comment]
Протестировано. Список транзакций на странице транзакций содержит не только инициализирующую транзакцию (транзакцию при оплате), но и операцию по возврату. Операции по возврату должны отображаться только в истории инициазирующей транзакции. Необходимо внести изменения в архитектуру проекта по хранению данных и отображения на странице транзакции. Открыть новый тикет.
