### ISSUE TITLE
Развернуть БД на сервере

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#51]
Развернуть postgres на сервере

**Конечный результат:** 
Добавить базу данных на сервере

**План решения:** 
- Создать дроплет digital ocean
- предоставить доступ к серверу с локального компьютера 
- добавить базу данных  postgres на сервер

**Мотивация:** 
На данный момент обновление и демонстрация проекта ведутся с локальных компьютеров вручную
**Критерии приёмки:**
> 

Планируемое время работы:
15 часов

**Comment by is-art** [comment]
@Zhanel-K 
Установил БД и докер на сервере.
Потратил 3 часа + 1 час  после  перезапуска сервера

**Comment by Zhanel-K** [comment]
Проверено наличие контейнера командой docker ps.
