### ISSUE TITLE
Добавить поля enum  в сущность заказа

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#52]
Добавить необходимые поля перечислений в сущность заказа ( статус и тип )
Исправить ошибки связанные с заменой сущности Transaction на Order.
**Время выполнения :**  8 часов

**Comment by Kitamuro** [comment]
Добавил доп. поля для статусов. Исправил ошибки.
Попробовал внедрить Criteria, Specifications. Возникли ошибки с фильтрацией
**Потрачено:** 8 часов

**Comment by is-art** [comment]
Проверено. Замечаний нет
