### ISSUE TITLE
Создать образ приложения и запушить в DockerHub (15h: 10h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#53]
**Описание:**
Создать Docker образ приложения и запушить в DockerHub чтобы иметь возможность запускать сервис из разных машин.

**Критерии приема:**
Возможность запускать сервис из любой машины в которой есть Docker.

**План реализации:**
1. Создание Docker образа приложения
2. Создать контейнер с помощью docker-compose
3. Запушить его в DockerHub
4. Выгрузить и запустить на наш сервер
5. При запуске нашего сервера иметь запущенный проект

**Comment by Kitamuro** [comment]
1. Создание Docker образа приложения (выполнено)
2. Создать контейнер с помощью docker-compose (выполнено)
3. Запушить его в DockerHub (выполнено)
4. Выгрузить и запустить на наш сервер (выполнено отчасти) 

Вышла ошибка при запуске docker-compose в ходе которой боясь разнести сервер начал искать доп информацию

**Comment by Kitamuro** [comment]
Запустил проект без IDEA, через консоль с помощью docker-compose. Работает корректно. Закрываю
