### ISSUE TITLE
Добавить возможность отображения списка  транзакций которые относятся к этому заказу

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#54]
**Описание:**
История транзакций сейчас отображается. Но все транзакции к заказу собираются в SQL запросе, сохраняются в сущность и передаются на сервер. 

Необходимо создать сущность Order , которая будет хранить список  транзакций, так же нужно будет добавить в эту сущность поле сумма заказа, и поле остаток суммы (  в случае если делается частичный возврат  остаток нужно изменять и фиксировать ). 

**Критерий приемки:**
 Я захожу в список заказов, кликаю на какой то заказ, и в истории платежа вижу все транзакции по этому заказу.

**Время выполнения** : 15 часов

**Comment by Kitamuro** [comment]
Изменил

**Comment by is-art** [comment]
Отрефакторил код. Добавил необходимые поля в сущность Order., добавил метод для парсинга из OrderDTO в Order  и обратно.  Добавил Exception OrderNotFound  что бы пробрасывать его в случае если не находим заказ. Теперь на странице заказов, при клике на заказ отправляется запрос на  Rest контроллер по адресу orders/{номер заказа} , на контроллере  собираю DTO и отправляю на фронт. Удалил лишний код.
**Потратил :** 5 часов

**Comment by is-art** [comment]
Проверил работает.
