### ISSUE TITLE
Добавить функционал резервирования денег ( холдирование) (15h:22h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#55]
**Описание:**
Реализовать функционал резервирования денег вместо мгновенного списания. 

**Критерий приемки:**
на странице оформления заказа я ввожу данные о заказе  , выбираю  опцию резервирования денег, запрос попадает на сервер, обрабатывается отправляется в банк. На странице операций вижу новую транзакцию со статусом зарезервирован , подтвержден

**Время выполнения:** 15 часов

**Comment by is-art** [comment]
Для более удобной демонстрации и тестирования на страницу оформления заказа добавил возможность выбора типа оплаты 
Потратил времени:  30 минут

**Comment by Zhanel-K** [comment]
Для добавления функционала потребовалось рефакторить предыдущую реализацию, так как концепция отправки запроса в Банк в не зависимости от типа транзакции. Кроме того, большая часть рефакторинга связана с изменением структуры хранения, вводом сущности  order, изменением структуры транзакции.

**Comment by is-art** [comment]
Проверил работает.
