### ISSUE TITLE
Добавить логи в проект(5h:3h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#57]
**Описание:**
Нужно добавить формирование и ежедневную выгрузку лог-файлов нашего проекта.
Логи (лог-файлы) — это файлы, содержащие системную информацию работы сервера или компьютера, в которые заносятся определенные действия пользователя или программы. 
Ежедневно создавать и выгружать лог-файлы каждую категорию отдельно(ошибки, предупреждения и тд в разных файлах). Если файл превышает поставленный обьем(условно 1гб) то делать перезапись в новый файл.

**Критерии приема:**
При запуске проекта создается лог-файл (условно name.log). В котором при каждой манипуляции в нашем проекте будут записываться изменения нашего проекта(ошибки, ответы, изменения, исключения и тд).

**План реализации:**
1. Изучить нужные инструменты для реализации.
2. Внедрить в проект
3. Добавить нужные зависимости и настройки

**Comment by is-art** [comment]
Изучал документацию и статья по логгированию в java. 
Добавил нужные зависимости и файл конфигурации для SLF4J , Logback 
Подключил логи к проекту.
**Потратил: 2 часа**

**Comment by is-art** [comment]
Изменил настройки logback теперь логи ежедневно переносятся в новый файл. Формат такой : Название файла - год-месяц-день.log

**Comment by Kitamuro** [comment]
При создании проекта создается log файл в который записываются вся информация системы проекта. Проверил. Закрываю.
