### ISSUE TITLE
Сделать поиск заказов по критериям (15h:10h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#59]
**Описание:**
Внесены изменения в поля и их типы в сущности Order.  В соответствии с этими изменениями необходимо отрефакторить методы фильтрации и поиска в репозитории и сервисе.

**Критерий приемки:**
На странице операций с заданными критериями поиска ( номер транзакции, название магазина, статус, сумму(опционально по диапазону)) отображаются заказы(Order), которые соответствует этим критериям. Если их нет, то отобразить сообщение пользователю. Поиск по строчным значениям (наименование магазина) сделать по частичному совпадению. Вывод результата нужно произвести с постраничным выводом (пагинацией).

**Подробный план реализации задачи:**
1. Рефакторинг OrderRepository (в соответствии с выбранным инструментом реализации).
2. Создать необходимые методы в OrderService.
3. Создать необходимые методы в OrderController.
4. Внести изменения (input, pagination, message) на странице заказов(order.html).

**Comment by Zhanel-K** [comment]
Функционал поиска выполнен с использованием  QueryDSL Predicate. Выполнены все запланированные критерии поисков, в том числе диапазон сумм и статус заказов. Внесены изменения в пагинацию при отфильтрованном списке ордеров. Внесено изменения в тип поля Amount c  int на Integer в связи с возникающей ошибкой "null for primitive type".

**Comment by Kitamuro** [comment]
Проверил фильтры поиска по отдельности и в комбо. Работает корректно согласно плану. Закрываю тикет.
