### ISSUE TITLE
ТЗ страница оплаты 

### ISSUE THREAD

**Issue by Zhanel-K** [AS-Java/Payment-Module#6]
Техническое задание страницы оплаты клиентом коммерсанта:

Описать подробно функционал страницы оплаты клиентом коммерсанта:
Источники: техзадание заказчика, протоколы встреч, аудио и диаграммы.

**Comment by is-art** [comment]
Описал что из себя представляет страница оплаты, какие данные содержит и для чего нужна. В ходе выполнения сложились вопросы по валидации введенных данных на странице оплаты.
[Ссылка на страницу оплаты](https://docs.google.com/document/d/1gfz0Yee9UmIscXvE3h5CSutzZbOymO9eHBBHrqzbSlU/edit)
