### ISSUE TITLE
Добавить регистрацию нового магазина в кабинете коммерсанта (10h:8h)

### ISSUE THREAD

**Issue by Kitamuro** [AS-Java/Payment-Module#62]
**Описание**
На странице магазины в кабинете коммерсанта добавить возможность регистрации нового магазина (интернет-ресурса) коммерсанта. 

**Критерии приема:**
1. Заходим на страницу магазинов. Нажимаем кнопку Создать магазин. На странице появляются поля для заполнения: 
1.1. Вид деятельности (с выбором и поиском), Наименование Сайта, Счет для выплат (с выбором), Регион продаж (с выбором), электронная почта для реестров. 
1.2. Ряд полей для реквизитов адреса. 
1.3. Ряд полей для связи с покупателем.
1.4. Ряд полей для реквизитов контактного лица.
2. После заполнения всех обязательных полей наживаем кнопку сохранить.
3. На странице появляется окно со ссылкой на данные интернет-магазина. Нажимаем на это окно.
4. Раскрывается страница с заполненными данными во вкладке О магазине.
5. В верхней части страницы рядом с наименованием магазина нажимаем кнопку редактирования. Редактируем какую-либо информацию и сохраняем.
5. Нажимаем вкладку Способы оплаты. На странице появляется информация о комиссии и способе списании средств (списывать сразу или блокировать на счет покупателя); 

**Требование к оформлению:**
Максимальное совпадение прототипу. Видео "Создание модуля приема платежей для сайта" и видео "Свойство модуля оплаты".

**План реализации:**
1. Создать новый класс Shop, ShopRepository, ShopService, ShopController.
2. В класс Commersant добавляем поле shops (List<Shop>, ManyToOne).
2. Добавить все необходимые поля (продумать какие-поля будут браться из Commersant).
3. Создать страницу Магазины со всеми необходимыми полями ввода и вкладками.
4. Создать ShopController, ShopService с необходимыми методами и все необходимые Post и Get запросы.

**Comment by Zhanel-K** [comment]
На текущий момент создание магазина пока не связано с Commersant
