### ISSUE TITLE
автоматизация поставки приложения на сервер с помощью GOCD(20h:20h)

### ISSUE THREAD

**Issue by is-art** [AS-Java/Payment-Module#66]

**Comment by Kitamuro** [comment]
Получилось вывести автоматическую поставку на тестовом дроплете. Но не получилось на сервере аттрактора. Попросил открыть порт и в дальнейшем запущу на сервере

**Comment by is-art** [comment]
Проверили на тестовом дроплете, работает, каждую минуту проверяет версию коммита , если есть изменения стягивает и перезапускает проект. Необходимо подключить на сервере attractor school
