### ISSUE TITLE
Создание страницы  оформления заказа 

### ISSUE THREAD

**Issue by Zhanel-K** [AS-Java/Payment-Module#8]
Необходимо создать страницу html, позволяющую симулировать оформление заказа клиента коммерсанта, с которой будет происходить вызов страницы оплаты. Часть работы необходимо будет выполнить совместно с разработчиком страницы оплаты сервиса.

**Comment by is-art** [comment]
[Добавил страницу для оформления заказа  ](21d6eefd80654031de79b1101e2c3261959691ee)
